requires 'CGI::Application';
requires 'CGI::Application::Plugin::TT';
requires 'CGI::Application::Plugin::DBH';
requires 'CGI::Session::Driver::mysql';
requires 'CGI::Application::Plugin::Session';
requires 'CGI::Application::Plugin::Authentication';
requires 'CGI::Application::Plugin::Forward';
requires 'CGI::Application::Server';

requires 'lib::abs';